---
title: "CS 770: Group Project"
author: "Srikanth Aravamuthan"
date: "12/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)
library(broom)
library(RecordLinkage)
library(janitor)
library(lme4)
library(broom.mixed)
library(forcats)
library(irr)

```

```{r}
text.a <- 
  c("December 17, 1903, is the birth date of all airplanes. Orville and Wilbur Wright started building gliders in 1900. In 1903, they built a motor and propeller for their glider. Orville made the first flight, which lasted 12 seconds, and flew 120 feet. Wilbur's flight was 852 feet in 59 seconds. These first flights in 1903 were just the start of the evolution of planes. By the year 1909, Bleriot had crossed the English Channel. By the year 1912, a two-piece plywood fuselage was built for greater strength. By the 1930s, the all-metal fuselage was tried, and it soon appeared in DC3s. From the Wrights' 1903 motor and prop came the engines for the 1950 turbojet that generated at least 19,600 pounds of thrust. The big Boeing 747 has four engines with 50,000 pounds of thrust each. The future holds an advanced super-sonic jet with a saving of almost 40 percent in fuel usage.")

text.b <- 
  c("Editing is a growing field of work in the service industry. Paid editing services may be provided by specialized editing firms or by self-employed (freelance) editors. Editing firms may employ a team of in-house editors, rely on a network of individual contractors or both. Such firms are able to handle editing in a wide range of topics and genres, depending on the skills of individual editors. The services provided by these editors may be varied and can include proofreading, copy editing, online editing, developmental editing, editing for search engine optimization (SEO), etc. Self-employed editors work directly for clients or offer their services through editing firms, or both. They may specialize in a type of editing and in a particular subject area. Those who work directly for authors and develop professional relationships with them are called authors' editors.")

```

```{r}
df <- 
  read.csv("Raw Data from App - Sheet1 (2).csv") %>% 
  clean_names() %>% 
  rename_all(~c("pid","control","code","experiment"))

```

```{r}
df.sim <- 
  df %>% 
  mutate(order = ifelse(str_detect(pid, "^CE"), "CE", "EC"),
         sim.control = ifelse(str_detect(pid, "^CE"), levenshteinSim(control, text.a), levenshteinSim(control, text.b)),
         sim.experiment = ifelse(str_detect(pid, "^EC"), levenshteinSim(experiment, text.a), levenshteinSim(experiment, text.b))) %>% 
  filter(pid != "CE12")

df.stat.sum <- 
  df.sim %>% 
  pivot_longer(sim.control:sim.experiment) %>% 
  group_by(name) %>% 
  summarize_at(vars(value), list(mean = mean, sd = sd)) %>% 
  mutate(pid = "mean") %>% 
  rename(value = mean) %>% 
  select(pid, everything(), -sd)

df.sim %>% 
  pivot_longer(sim.control:sim.experiment) %>% 
  do(tidy(t.test(value ~ name, data = ., paired = TRUE, alternative = "greater")))

```

```{r}
df.sim %>% 
  pivot_longer(sim.control:sim.experiment) %>% 
  ggplot() +
  geom_line(
    aes(
      x = name,
      y = value,
      group = pid,
      color = order,
      linetype = order
    ),
    size = 1,
    alpha = 0.25
  ) +
  geom_line(
    data = df.stat.sum,
    aes(
      x = name,
      y = value,
      group = pid,
      # color = order,
      # linetype = order
    ),
    color = "#C77CFF",
    size = 1,
    alpha = 0.25
  ) +
  geom_vline(xintercept = 1:2,
             size = 1,
             alpha = 0.25) +
  geom_point(
    aes(
      x = name,
      y = value,
      # color = name,
      color = order,
      # shape = order
    ),
    size = 3,
    alpha = 0.75) +
  geom_point(
    data = df.stat.sum,
    aes(
      x = name,
      y = value,
      # color = name,
      # color = order,
      # shape = order
      shape = pid,
    ),
    color = "#C77CFF",
    size = 6,
    alpha = 0.5) +
  scale_x_discrete(labels = c("Control", "Experiment")) +
  # scale_color_discrete(labels = c("Control", "Experiment")) +
  scale_color_discrete(labels = c("CE", "EC")) +
  # scale_shape_discrete(labels = c("CE", "EC")) +
  scale_shape_manual(values = 18,
                     labels = c("Mean")) +
  scale_linetype_discrete(labels = c("CE", "EC")) +
  labs(x = "Study Group",
       y = "Similarity Score",
       # color = "Study Group",
       color = "Order",
       # shape = "Order",
       shape = "Summary Statistic",
       linetype = "Order") +
  theme_bw()

# ggsave("user-interruption-1.png", dpi = 1200)

```



```{r eval=FALSE}
df.post <- 
  read_csv("Post-Study Survey (Responses) - Form Responses 1 (2).csv") %>% 
  clean_names()

df.q <- 
  df.post %>% 
  select(participant_id:what_was_the_temperature_in_chicago) %>% 
  pivot_longer(what_day_and_time_was_dinner:what_was_the_temperature_in_chicago) %>% 
  group_by(participant_id) %>% 
  mutate(group = 
           case_when(
             str_detect(participant_id, "^CE") & between(row_number(), 1, 7) ~ "control",
             str_detect(participant_id, "^CE") & between(row_number(), 8, 14) ~ "experiment",
             str_detect(participant_id, "^EC") & between(row_number(), 1, 7) ~ "experiment",
             str_detect(participant_id, "^EC") & between(row_number(), 8, 14) ~ "control",
           ),
         question_id = str_c("Q", str_pad(row_number(), 2, pad = "0"))
  ) %>% 
  ungroup() %>% 
  rename(question = name,
         answer = value) %>% 
  select(participant_id, group, question_id, question, answer)

df.code <- 
  df %>% 
  select(pid, code) %>% 
  separate(code, str_c(letters[1:5], 1), sep = "\n") %>% 
  mutate(a2 = a1,
         e2 = e1) %>% 
  select(pid, sort(current_vars())) %>% 
  pivot_longer(a1:e2) %>% 
  separate(value, c("icon", "vibration", "duration", "font", "color"), sep = "(?<=[0-1])") %>% 
  group_by(pid) %>% 
  mutate(group = "experiment",
         qid = ifelse(str_detect(pid, "CE"), str_c("Q", str_pad(7 + row_number(), 2, pad = "0")), str_c("Q", str_pad(row_number(), 2, pad = "0")))) %>% 
  ungroup() %>% 
  mutate_at(vars(icon, vibration, color), ~ifelse(. == "0", "1", "0")) %>% 
  # mutate_at(vars(icon:color), ~as.numeric(.)) %>% 
  # mutate_at(vars(icon, vibration, color), ~1 - .)
  select(pid, group, qid, icon:color)

df.q %>%
  left_join(df.code,
            by = c("participant_id" = "pid",
                   "question_id" = "qid",
                   "group")) %>%
  write_csv("master.csv")

```



```{r}
df.master <- 
  read_csv("master.csv") %>%
#   mutate(question_id =
#            str_replace(question_id, "[[:digit:]]+$", str_pad(str_extract(question_id, "[[:digit:]]+$"), 2, pad = "0"))) %>%
  mutate_at(vars(icon:color), ~as.character(.))

```



```{r}
df.master %>% 
  do(tidy(glmer(score ~ font + color + duration + icon + vibration + (1|participant_id) + (1|question_id), data = ., family = binomial), conf.int=TRUE))

df.master %>% 
  do(tidy(glmer(score ~ font + color + duration + icon + vibration + (1|question_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE))

df.master %>% 
  do(tidy(glmer(score ~ font + color + duration + icon + vibration + (1|participant_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE))



df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glm(score ~ font, data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glm(score ~ color, data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glm(score ~ duration, data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glm(score ~ icon, data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glm(score ~ vibration, data = ., family = binomial)))



df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glmer(score ~ font + (1|participant_id) + (1|question_id), data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glmer(score ~ color + (1|participant_id) + (1|question_id), data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glmer(score ~ duration + (1|participant_id) + (1|question_id), data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glmer(score ~ icon + (1|participant_id) + (1|question_id), data = ., family = binomial)))

df.master %>% 
  mutate_at(vars(icon:color), ~replace_na(., "-1")) %>% 
  do(tidy(glmer(score ~ vibration + (1|participant_id) + (1|question_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE))



```

```{r}
df.coef <- 
  df.master %>% 
  do(tidy(glmer(score ~ font + color + duration + icon + vibration + (1|participant_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE))

df.coef %>% 
  filter(effect == "fixed") %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = str_remove_all(term, "[[:digit:]]"),
         term = str_to_title(term)) %>% 
  mutate_at(vars(estimate, conf.low, conf.high), ~exp(.)) %>%
  mutate(
    term = fct_reorder(term, estimate),
    # term = fct_rev(term)
  ) %>% 
  ggplot() +
  geom_linerange(aes(xmin = conf.low,
                     xmax = conf.high,
                     y = term),
                 lineend = "round",
                 color = "#F8766D",
                 # color = "#00BFC4",
                 size = 1.5,
                 alpha = 0.25) +
  geom_point(
    aes(
      x = estimate,
      y = term
    ),
    # color = "#00BFC4",
    color = "#F8766D",
    shape = 21,
    fill = "white",
    size = 3,
    stroke = 1.5,
    # alpha = 0.5
  ) +
  geom_vline(xintercept = 1,
             linetype = "dashed") +
  scale_y_discrete(labels = c("Font" = "Font Family", 
                              "Color" = "Background Color", 
                              "Duration" = "Duration of Visibility", 
                              "Icon" = "Icon Reinforcement", 
                              "Vibration" = "Haptic Feedback")) +
  scale_x_continuous(breaks = c(0, 0.25, 0.5, 1, 2, 4),
                     trans = "log") +
  labs(x = "Odds Ratio",
       y = "Term") +
  theme_bw()

# ggsave("user-attention-1.png", dpi = 1200)

```



```{r}
df.coef <- 
  df.master %>% 
  select(participant_id, question_id, icon:score) %>% 
  do(tidy(glmer(score ~ (font + color + duration + icon + vibration)^2 + (1|participant_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE))

df.coef %>% 
  filter(effect == "fixed") %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = str_remove_all(term, "[[:digit:]]"),
         term = str_replace_all(term, ":", " : "),
         term = str_to_title(term)) %>% 
  mutate(effect = ifelse(str_detect(term, " : "), "interaction", "main"),
         effect = str_to_title(effect)) %>% 
  mutate_at(vars(estimate, conf.low, conf.high), ~exp(.)) %>%
  mutate(
    term = fct_reorder(term, estimate),
    effect = fct_rev(effect)
  ) %>% 
  ggplot() +
  geom_linerange(
    aes(
      xmin = conf.low,
      xmax = conf.high,
      y = term,
      color = effect
    ),
    lineend = "round",
    # color = "#F8766D",
    # color = "#00BFC4",
    size = 1.5,
    alpha = 0.25
  ) +
  geom_point(
    aes(
      x = estimate,
      y = term,
      color = effect
    ),
    # color = "#00BFC4",
    # color = "#F8766D",
    shape = 21,
    fill = "white",
    size = 3,
    stroke = 1.5,
    # alpha = 0.5
  ) +
  geom_vline(xintercept = 1,
             linetype = "dashed") +
  # scale_y_discrete(labels = c("Font" = "Font Family", 
  #                             "Color" = "Background Color", 
  #                             "Duration" = "Duration of Visibility", 
  #                             "Icon" = "Icon Reinforcement", 
  #                             "Vibration" = "Haptic Feedback")) +
  scale_x_continuous(breaks = c(0, 0.25, 1, 4, 16, 64),
                     trans = "log") +
  scale_color_manual(values = c("#F8766D", "#00BFC4")) +
  labs(x = "Odds Ratio",
       y = "Term",
       color = "Effect") +
  theme_bw()

# ggsave("user-attention-2.png", dpi = 1200)

```



```{r}
df.post <- 
  read_csv("Post-Study Survey (Responses) - Form Responses 1 (2).csv") %>% 
  clean_names()

df.post %>% 
  select_if(is.numeric) %>% 
  mutate_all(~ifelse(. >= 3, 1, 0)) %>% 
  pivot_longer(everything()) %>% 
  mutate(notification = 
           case_when(
             str_detect(name, "font") ~ "font",
             str_detect(name, "color") ~ "color",
             str_detect(name, "duration") ~ "duration",
             str_detect(name, "icon") ~ "icon",
             str_detect(name, "vibration") ~ "vibration",
           ),
         action = 
           case_when(
             str_detect(name, "completing_the_primary_task") ~ "completing_the_primary_task",
             str_detect(name, "retain_content") ~ "retain_content"
           )
  ) %>% 
  group_by(notification, action) %>% 
  do(x = tidy(binom.test(sum(.$value), nrow(.), alternative = "two.sided"))) %>% 
  unnest() %>% 
  mutate(
    notification = fct_relevel(notification, c("font", "color", "duration", "icon", "vibration")),
    notification = fct_rev(notification),
    action = fct_relevel(action, c("retain_content", "completing_the_primary_task")),
    # action = fct_rev(action)
  ) %>% 
  ggplot() +
  geom_linerange(
    aes(
      xmin = conf.low,
      xmax = conf.high,
      y = notification,
      color = action
    ),
    position = position_dodge2(width = 0.25,
                               reverse = TRUE),
    lineend = "round",
    size = 1.5,
    alpha = 0.25
  ) +
  geom_point(
    aes(
      x = estimate,
      y = notification,
      color = action
    ),
    position = position_dodge2(width = 0.25,
                               reverse = TRUE),
    shape = 21,
    fill = "white",
    size = 3,
    stroke = 1,
    # alpha = 0.5
  ) +
  geom_vline(xintercept = 0.5,
             linetype = "dashed") +
  scale_y_discrete(labels = c("font" = "Font Family",
                              "color" = "Background Color",
                              "duration" = "Duration of Visibility",
                              "icon" = "Icon Reinforcement",
                              "vibration" = "Haptic Feedback")) +
  scale_color_discrete(labels = c("retain_content" = "Information Recall",
                                  "completing_the_primary_task" = "Text Transcription")) +
  labs(x = "Proportion",
       y = "Notification Attribute",
       color = "Action") +
  theme_bw()

# ggsave("user-perception-1.png", dpi = 1200)

```



```{r}
df.post <- 
  read_csv("Post-Study Survey (Responses) - Form Responses 1 (2).csv") %>% 
  clean_names()

df.master <- 
  read_csv("master.csv") %>% 
  # mutate(question_id = 
  #          str_replace(question_id, "[[:digit:]]+$", str_pad(str_extract(question_id, "[[:digit:]]+$"), 2, pad = "0"))) %>%
  mutate_at(vars(icon:color), ~as.character(.))

notfication.attribute <- c("font", "color", "duration", "icon", "vibration")
action <- c("transcribe_text", "recall_information")

names.user.perception <- 
  expand_grid(notfication.attribute, action) %>% 
  mutate(x = str_c(notfication.attribute, action, sep = "_")) %>% 
  select(x) %>% 
  pull()

df.coef <- 
  df.post %>% 
  # select(participant_id, where(is.numeric)) %>% 
  # rename_all(~c("participant_id", names.user.perception)) %>% 
  select(participant_id, (ends_with("recall_information") & where(is.numeric))) %>% 
  # rename_all(~c("participant_id", names.user.perception)) %>% 
  rename_all(~c("participant_id", notfication.attribute)) %>% 
  # mutate(group = str_sub(participant_id, 1, 2)) %>% 
  mutate_if(is.numeric, ~ifelse(. >= 3, "1", "0")) %>% 
  left_join(df.master %>% 
              select(participant_id, group, question_id, icon:color, score),
            by = "participant_id") %>% 
  pivot_longer(ends_with(".x"),
               names_to = "name.x",
               values_to = "value.x") %>% 
  pivot_longer(ends_with(".y"),
               names_to = "name.y",
               values_to = "value.y") %>% 
  mutate(name.x = str_remove(name.x, "\\.x"),
         name.y = str_remove(name.y, "\\.y")) %>% 
  filter(name.x == name.y) %>% 
  group_by(name.x, name.y) %>% 
  do(tidy(glmer(score ~ value.x + value.y + (1|participant_id), data = ., family = binomial, control = glmerControl(optimizer="bobyqa")), conf.int=TRUE)) %>% 
  ungroup() %>% 
  filter(effect != "ran_pars") %>% 
  filter(term != "(Intercept)") %>% 
  select(-effect, -group)

df.coef %>% 
  mutate(
    notification = name.x,
    action = 
      case_when(
        term == "value.x1" ~ "user_attention",
        term == "value.y1" ~ "user_perception",
      )
  ) %>% 
  select(notification, everything(), -name.x, -name.y, -term) %>% 
  mutate(
    notification = fct_relevel(notification, c("font", "color", "duration", "icon", "vibration")),
    notification = fct_rev(notification),
    action = fct_relevel(action, c("user_attention", "user_perception")),
    # action = fct_rev(action)
  ) %>% 
  mutate_at(vars(estimate, conf.low, conf.high), ~exp(.)) %>%
  ggplot() +
  geom_linerange(
    aes(
      xmin = conf.low,
      xmax = conf.high,
      y = notification,
      color = action
    ),
    position = position_dodge2(width = 0.25,
                               reverse = TRUE),
    lineend = "round",
    size = 1.5,
    alpha = 0.25
  ) +
  geom_point(
    aes(
      x = estimate,
      y = notification,
      color = action
    ),
    position = position_dodge2(width = 0.25,
                               reverse = TRUE),
    shape = 21,
    fill = "white",
    size = 3,
    stroke = 1,
    # alpha = 0.5
  ) +
  geom_vline(xintercept = 1,
             linetype = "dashed") +
  scale_y_discrete(labels = c("font" = "Font Family",
                              "color" = "Background Color",
                              "duration" = "Duration of Visibility",
                              "icon" = "Icon Reinforcement",
                              "vibration" = "Haptic Feedback")) +
  scale_color_discrete(labels = c("user_attention" = "User Attention",
                                  "user_perception" = "User Perception")) +
  labs(x = "Odds Ratio",
       y = "Notification Attribute",
       color = "Action") +
  theme_bw()

```



```{r eval=FALSE}
read_csv("Post-Study Survey (Responses) - Form Responses 1 (2).csv") %>% 
  clean_names() %>% 
  select(participant_id, last_col(offset = 4):last_col()) %>% 
  rename_all(~c("participant_id", "font", "color", "duration", "icon", "vibration")) %>% 
  pivot_longer(font:vibration) %>%
  separate_rows(value, sep = "[\\.\\,]", convert = TRUE) %>% 
  mutate(value = str_remove(value, "^ "),
         value = str_remove(value, " $")) %>% 
  filter(str_detect(value, " ")) %>% 
  filter(value != "") %>% 
  group_by(participant_id, name) %>% 
  mutate(line = row_number()) %>% 
  ungroup() %>% 
  add_column(code_1 = NA,
             code_2 = NA,
             code_3 = NA,
             key_phrase = NA) %>% 
  select(participant_id, name, line, value, everything()) %>% 
  write_csv("free-response.csv")

```



```{r eval=FALSE}
df.free.response.x <- 
  read_csv("2_free-response_zach_thru_104.csv") %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>% 
  select(-code_id) %>% 
  mutate(value.x = 1)

df.free.response.y <- 
  read_csv("2_free-response_brahma_thru_104.csv") %>% 
  mutate(code_3 = NA_character_) %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>% 
  select(-code_id) %>% 
  mutate(value.y = 1)

df.irr <- 
  df.free.response.x %>% 
  full_join(df.free.response.y) %>% 
  mutate_at(vars(value.x:value.y),
            ~ifelse(is.na(.), 0, .)) %>% 
  mutate_at(vars(value.x:value.y),
            ~ifelse(. == 1, code, .)) %>% 
  select(value.x:value.y)

df.irr %>% 
  kappa2()

```



```{r}
df.free.response.x <- 
  read_csv("2_free-response_zach_thru_104.csv") %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>%
  select(-code_id) %>% 
  separate(code, c("code", "subcode"), "::") %>% 
  select(-subcode) %>%
  # select(-code) %>% 
  mutate(value.x = "1") %>% 
  distinct()

df.free.response.y <- 
  read_csv("2_free-response_brahma_thru_104.csv") %>% 
  mutate(code_3 = NA_character_) %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>%
  select(-code_id) %>% 
  separate(code, c("code", "subcode"), "::") %>% 
  select(-subcode) %>%
  # select(-code) %>% 
  mutate(value.y = "1") %>% 
  distinct()

df.irr <- 
  df.free.response.x %>% 
  full_join(df.free.response.y) %>% 
  mutate_at(vars(value.x:value.y),
            ~ifelse(is.na(.), "0", .)) %>% 
  mutate_at(vars(value.x:value.y),
            ~ifelse(. == "1", code, .)) %>%
  # mutate_at(vars(value.x:value.y),
  #           ~ifelse(. == "1", subcode, .)) %>%
  select(value.x:value.y)

df.irr %>% 
  kappa2()

df.free.response.x %>% 
  full_join(df.free.response.y) %>% 
  mutate(
    rater =
      case_when(
        value.x == 1 & value.y == 1 ~ "Raters 1 & 2",
        value.x == 1 ~ "Rater 1",
        value.y == 1 ~ "Rater 2"
      )
  ) %>% 
  mutate_at(vars(name, code), ~str_to_title(.)) %>% 
  mutate(name = fct_relevel(name, c("Font", "Color", "Duration", "Icon", "Vibration"))) %>% 
  separate(code, c("sentiment", NA), "\\ ", remove = FALSE) %>% 
  ggplot() +
  geom_bar(aes(x = code,
               fill = rater,
               color = rater),
           alpha = 0.5) +
  labs(x = "Code",
       y = "Count",
       fill = "",
       color = "") +
  facet_grid(vars(name), vars(sentiment), scales = "free_x") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.x = element_text(hjust = 0.67,
                                   angle = 15))

# ggsave("user-perception-2.png", dpi = 1200)

```



```{r}
df.free.response.x <- 
  read_csv("2_free-response_zach_thru_104.csv") %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>%
  select(-code_id) %>% 
  separate(code, c("code", "subcode"), "::") %>% 
  # select(-subcode) %>%
  # select(-code) %>%
  mutate(value.x = "1") %>% 
  distinct()

df.free.response.y <- 
  read_csv("2_free-response_brahma_thru_104.csv") %>% 
  mutate(code_3 = NA_character_) %>% 
  select(-value, -key_phrase) %>% 
  pivot_longer(contains("code"),
               names_to = "code_id",
               values_to = "code") %>% 
  filter(!is.na(code)) %>%
  select(-code_id) %>% 
  separate(code, c("code", "subcode"), "::") %>% 
  # select(-subcode) %>%
  # select(-code) %>%
  mutate(value.y = "1") %>% 
  distinct()

df.irr <- 
  df.free.response.x %>% 
  full_join(df.free.response.y) %>% 
  mutate_at(vars(value.x:value.y),
            ~ifelse(is.na(.), "0", .)) %>% 
  # mutate_at(vars(value.x:value.y),
  #           ~ifelse(. == "1", code, .)) %>%
  mutate_at(vars(value.x:value.y),
            ~ifelse(. == "1", subcode, .)) %>%
  select(value.x:value.y)

df.irr %>% 
  kappa2()

df.free.response.x %>% 
  full_join(df.free.response.y) %>% 
  mutate(
    rater =
      case_when(
        value.x == 1 & value.y == 1 ~ "Raters 1 & 2",
        value.x == 1 ~ "Rater 1",
        value.y == 1 ~ "Rater 2"
      )
  ) %>% 
  mutate_at(vars(name, code, subcode), ~str_to_title(.)) %>% 
  mutate_at(vars(subcode), ~str_replace_all(., "Appt", "Apt")) %>% 
  mutate_at(vars(subcode), ~str_replace_all(., "Inappt", "Inapt")) %>% 
  mutate_at(vars(subcode), ~str_replace_all(., "Background", "Color")) %>% 
  mutate(name = fct_relevel(name, c("Font", "Color", "Duration", "Icon", "Vibration"))) %>%
  separate(code, c("sentiment", NA), "\\ ", remove = FALSE) %>% 
  ggplot() +
  geom_bar(aes(x = subcode,
               fill = rater,
               color = rater),
           alpha = 0.5) +
  labs(x = "Subcode",
       y = "Count",
       fill = "",
       color = "") +
  facet_grid(vars(name), vars(sentiment), scales = "free_x", space = "free_x") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "white"),
        axis.text.x = element_text(hjust = 0.67,
                                   angle = 15))

# ggsave("user-perception-3.png", dpi = 1200)

```
